# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
# rssFullContent = true
favicon = "favicon.png"

[footer]
since = 2025
customText = '<a href="http://beian.miit.gov.cn/" target="_blank">æ²ªICPå¤‡2024062997å·-1</a>'

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸ¥"
subtitle = "ç­‰å¤©ç‹æ˜Ÿçš„åœ°è¡¨æ¸©åº¦åˆ°è¾¾23â„ƒ,æˆ‘ä»¬å°±å»çœ‹ä¸€åœºæ˜Ÿè¾°å½’æš®å§"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = true
math = true
readingTime = true

[article.license]
enabled = false

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[defaultImage.opengraph]
enabled = true
local = true
src = "/img/Uranus23.jpg"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true
